### ISSUE TITLE
Reorder slides from session one to clear up potential confusion

### ISSUE THREAD

**Issue by rhewitt22** [mizmay/web-map-quickstart#1]
For session one I think slides #29 and #30 should be swapped.  Slide 29 explains that most of the functionality we used to lean on Flash for is now available through HTML5.  Slide #30 reads "Doesn't work on smartphones or tablets," which might confuse novice readers that HTML5 rather than flash doesn't work on these devices.

If reordering isn't ideal I would just try to make that point explicit.

Well done!

**Comment by mizmay** [comment]
Moved the HTML5 comment down two slides. Thanks for the feedback! We are revamping the whole course currently.
