### ISSUE TITLE
Session 4

### ISSUE THREAD

**Issue by mizmay** [mizmay/web-map-quickstart#20]
Yes on the geodata formats! I'm gonna vote no on geodesy and I think we've covered the lets make a map one. Yes on the Leaflet/GeoJSON one. Would be nice to also have an exercise that throws data from an API on a web map and I found a couple of Mapbox Studio tutorials we can incorporate.

**Comment by lyzidiamond** [comment]
Some decks we can pull from:
- [Introduction to Geographic Data Formats](http://maptime.github.io/geodata)
- [The Wild World of Geodesy](http://lyzidiamond.com/geodesy)
- [Using GeoJSON in Web Maps](http://lyzidiamond.com/geojson-in-maps)
- [Hell Yes, Leaflet! (or, making your first web map)](http://lyzidiamond.com/leaflet)

Tutorials:
- [Learn GeoJSON](http://lyzidiamond.com/learn-geojson) + [GitHub repo](http://github.com/lyzidiamond/learn-geojson)

I'll probably think of more and add them here.

**Comment by mizmay** [comment]
Yes on the geodata formats! I'm gonna vote no on geodesy and I think we've covered the lets make a map one. Yes on the Leaflet/GeoJSON one. Would be nice to also have an exercise that throws data from an API on a web map and I found a couple of Mapbox Studio tutorials we can incorporate.

**Comment by mizmay** [comment]
Oh yeah and no idea whether github will be awesome or too much! Look forward to your further development on that idea.

**Comment by lyzidiamond** [comment]
I think we'll do the first part geographic data formats, the second part geojson in web maps with some explanations about how the internet works.

**Comment by mizmay** [comment]
Mapbox Studio tutorial just in case: http://www.digital-geography.com/mapbox-studio-tutorial-1-installation-gui-first-map/#.VGGVilNdXmE

I found another one yesterday but now it has escaped.

**Comment by mizmay** [comment]
Oh bc it was a Tilemill2 exercise: http://twelch.github.io/articles/visualizing-landslide-2-tilemill2/

Good class Lyzi!
